import type { MarkdownEditorLimits, MarkdownEditorTexts, MarkdownEditorView, MarkdownRenderTexts } from "./types";

export const MARKDOWN_EDITOR_VIEWS: readonly MarkdownEditorView[] = ["source", "split", "preview"];

export const DEFAULT_MARKDOWN_EDITOR_LIMITS: MarkdownEditorLimits = {
  tableRows: 20,
  tableColumns: 10,
};

export const DEFAULT_MARKDOWN_RENDER_TEXTS: MarkdownRenderTexts = {
  alertTitles: {
    info: "Nota",
    success: "Consejo",
    important: "Importante",
    warning: "Advertencia",
    error: "Precaución",
  },
  diagram: {
    label: "Diagrama",
    rendering: "Dibujando el diagrama…",
    error: "No se pudo dibujar el diagrama",
    expand: "Ver a tamaño completo",
    close: "Cerrar",
  },
  formula: {
    error: "La fórmula tiene un error",
  },
  footnotes: "Notas al pie",
  backToReference: "Volver al texto",
};

export const DEFAULT_MARKDOWN_EDITOR_TEXTS: MarkdownEditorTexts = {
  sourceLabel: "Texto en Markdown",
  placeholder: "Escribe aquí en Markdown…",
  previewLabel: "Vista previa",
  viewSwitchLabel: "Vista",
  viewLabels: {
    source: "Editor",
    split: "Dividida",
    preview: "Vista previa",
  },
  toolbarLabel: "Herramientas de formato",
  search: {
    find: "Buscar",
    replace: "Reemplazar",
    next: "Siguiente",
    previous: "Anterior",
    all: "Todos",
    matchCase: "Mayúsculas",
    regexp: "Expresión regular",
    byWord: "Palabra completa",
    replaceOne: "Reemplazar",
    replaceAll: "Reemplazar todo",
    close: "Cerrar",
    goToLine: "Ir a la línea",
    go: "Ir",
    currentMatch: "Coincidencia actual",
    onLine: "en la línea",
    replacedMatchOnLine: "Se reemplazó la coincidencia de la línea $",
    replacedMatches: "Se reemplazaron $ coincidencias",
  },
  outline: {
    title: "Índice",
    empty: "El documento todavía no tiene títulos.",
  },
  dialogs: {
    cancel: "Cancelar",
    insert: "Insertar",
    close: "Cerrar",
    optional: "opcional",
    missingUrl: "Escribe una dirección.",
    invalidUrl: "La dirección no es válida.",
    unsafeUrl: "Esa dirección no está permitida.",
    missingNote: "Escribe el texto de la nota.",
    link: {
      title: "Insertar enlace",
      text: "Texto",
      url: "Dirección",
      urlPlaceholder: "https://ejemplo.com",
      linkTitle: "Título al pasar el cursor",
    },
    reference: {
      title: "Insertar referencia",
      kind: "Tipo",
      linkKind: "Enlace por referencia",
      footnoteKind: "Nota al pie",
      text: "Texto",
      url: "Dirección",
      note: "Nota",
      id: "Identificador",
      idHint: "Si lo dejas vacío se usa {id}.",
      duplicateId: "Ese identificador ya existe en el documento.",
    },
    image: {
      title: "Insertar imagen",
      urlTab: "Desde una dirección",
      fileTab: "Subir archivo",
      url: "Dirección de la imagen",
      file: "Archivo",
      chooseFile: "Elegir imagen",
      alt: "Texto alternativo",
      altHint: "Describe la imagen para quien no puede verla.",
      imageTitle: "Título",
      preview: "Vista previa",
      uploading: "Subiendo…",
      uploadFailed: "No se pudo subir la imagen. Prueba de nuevo.",
      missingFile: "Elige una imagen.",
      missingAlt: "Escribe un texto alternativo.",
      invalidType: "Ese tipo de archivo no está permitido.",
      tooLarge: "La imagen supera el tamaño máximo ({size}).",
      placeholder: "Subiendo imagen…",
    },
    code: {
      title: "Insertar bloque de código",
      language: "Lenguaje",
      searchLanguage: "Buscar lenguaje",
      noLanguages: "No hay lenguajes con ese nombre",
      code: "Código",
    },
    table: {
      title: "Insertar tabla",
      rows: "Filas",
      columns: "Columnas",
      alignment: "Alineación",
      left: "Izquierda",
      center: "Centro",
      right: "Derecha",
      preview: "Vista previa de la tabla",
      limitHint: "Hasta {rows} filas y {columns} columnas.",
      clamped: "Se ajustó al máximo permitido.",
    },
    emoji: {
      title: "Insertar emoji",
      search: "Buscar emoji",
      recent: "Recientes",
      noResults: "No hay emoji con ese nombre",
      loading: "Cargando emoji…",
    },
    diagram: {
      title: "Insertar diagrama",
      template: "Plantilla",
      code: "Código Mermaid",
      preview: "Vista previa del diagrama",
    },
    guide: {
      title: "Guía de Markdown",
      write: "Escribir",
      insert: "Insertar",
      typed: "Se escribe",
      rendered: "Se ve",
      empty: "Ninguna herramienta de esta barra escribe esta parte.",
    },
    htmlEntityTitle: "Insertar símbolo",
  },
  clearDialog: {
    title: "¿Borrar todo el contenido?",
    description: "Se borra todo el texto del editor. Puedes recuperarlo con Deshacer.",
    confirm: "Borrar todo",
    cancel: "Cancelar",
  },
  moreTools: "Más herramientas",
  tools: {
    undo: "Deshacer",
    redo: "Rehacer",
    bold: "Negrita",
    italic: "Cursiva",
    strikethrough: "Tachado",
    inlineCode: "Código en línea",
    uppercase: "MAYÚSCULAS",
    lowercase: "minúsculas",
    capitalize: "Cada Palabra En Mayúscula",
    heading: "Títulos",
    headingLevel: "Título {level}",
    quote: "Cita",
    bulletList: "Lista con viñetas",
    orderedList: "Lista numerada",
    taskList: "Lista de tareas",
    horizontalRule: "Línea horizontal",
    dateTime: "Fecha y hora",
    search: "Buscar",
    replace: "Buscar y reemplazar",
    goToLine: "Ir a línea",
    link: "Enlace",
    reference: "Referencia",
    image: "Imagen",
    codeBlock: "Bloque de código",
    table: "Tabla",
    diagram: "Diagrama",
    formula: "Fórmula",
    emoji: "Emoji",
    htmlEntity: "Símbolos",
    outline: "Índice",
    fullscreen: "Pantalla completa",
    clear: "Borrar todo",
    guide: "Guía de Markdown",
    alert: "Avisos",
    alertVariants: {
      info: "Nota",
      success: "Consejo",
      important: "Importante",
      warning: "Advertencia",
      error: "Precaución",
    },
  },
};

export const DEFAULT_ACCEPTED_IMAGE_TYPES: readonly string[] = ["image/png", "image/jpeg", "image/gif", "image/webp"];

export const DEFAULT_MAX_IMAGE_BYTES = 5 * 1024 * 1024;

export const MARKDOWN_EDITOR_DEFAULTS = {
  view: "split",
  syncScroll: true,
  tools: "full",
  toolbarPlacement: "shared",
} as const;
