import type { EmojiCategory } from "./emoji-types";

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  {
    id: "smileys",
    label: "Caras",
    emojis: [
      { emoji: "😀", name: "sonrisa cara feliz", keywords: "sonrisa cara feliz grinning face" },
      { emoji: "😃", name: "sonrisa grande feliz", keywords: "sonrisa grande feliz smiling face with open mouth" },
      { emoji: "😄", name: "sonrisa ojos felices", keywords: "sonrisa ojos felices smiling face with open mouth and smiling eyes" },
      { emoji: "😁", name: "sonrisa dientes", keywords: "sonrisa dientes grinning face with smiling eyes" },
      { emoji: "😆", name: "risa carcajada", keywords: "risa carcajada smiling face with open mouth and tightly-closed eyes" },
      { emoji: "😅", name: "sonrisa sudor nervios", keywords: "sonrisa sudor nervios smiling face with open mouth and cold sweat" },
      { emoji: "🤣", name: "risa rodando carcajada", keywords: "risa rodando carcajada rolling on the floor laughing" },
      { emoji: "😂", name: "lágrimas de risa", keywords: "lagrimas de risa face with tears of joy" },
      { emoji: "🙂", name: "sonrisa leve", keywords: "sonrisa leve slightly smiling face" },
      { emoji: "😉", name: "guiño", keywords: "guiño winking face" },
      { emoji: "😊", name: "sonrojado contento", keywords: "sonrojado contento smiling face with smiling eyes" },
      { emoji: "😇", name: "ángel inocente", keywords: "angel inocente smiling face with halo" },
      { emoji: "🥰", name: "enamorado corazones", keywords: "enamorado corazones smiling face with smiling eyes and three hearts" },
      { emoji: "😍", name: "ojos de corazón enamorado", keywords: "ojos de corazon enamorado smiling face with heart-shaped eyes" },
      { emoji: "🤩", name: "asombro estrellas", keywords: "asombro estrellas grinning face with star eyes" },
      { emoji: "😘", name: "beso", keywords: "beso face throwing a kiss" },
      { emoji: "😋", name: "delicioso rico", keywords: "delicioso rico face savouring delicious food" },
      { emoji: "😛", name: "lengua afuera", keywords: "lengua afuera face with stuck-out tongue" },
      { emoji: "😜", name: "guiño lengua", keywords: "guiño lengua face with stuck-out tongue and winking eye" },
      { emoji: "🤪", name: "loco", keywords: "loco grinning face with one large and one small eye" },
      { emoji: "🤗", name: "abrazo", keywords: "abrazo hugging face" },
      { emoji: "🤔", name: "pensando duda", keywords: "pensando duda thinking face" },
      { emoji: "🤨", name: "ceja levantada sospecha", keywords: "ceja levantada sospecha face with one eyebrow raised" },
      { emoji: "😐", name: "neutral serio", keywords: "neutral serio neutral face" },
      { emoji: "😑", name: "sin expresión", keywords: "sin expresion expressionless face" },
      { emoji: "😶", name: "sin boca callado", keywords: "sin boca callado face without mouth" },
      { emoji: "🙄", name: "ojos en blanco", keywords: "ojos en blanco face with rolling eyes" },
      { emoji: "😏", name: "sonrisa pícara", keywords: "sonrisa picara smirking face" },
      { emoji: "😬", name: "mueca incómodo", keywords: "mueca incomodo grimacing face" },
      { emoji: "😌", name: "aliviado", keywords: "aliviado relieved face" },
      { emoji: "😔", name: "pensativo triste", keywords: "pensativo triste pensive face" },
      { emoji: "😴", name: "dormido sueño", keywords: "dormido sueño sleeping face" },
      { emoji: "😷", name: "mascarilla enfermo", keywords: "mascarilla enfermo face with medical mask" },
      { emoji: "🤒", name: "fiebre termómetro", keywords: "fiebre termometro face with thermometer" },
      { emoji: "🤯", name: "cabeza explota sorpresa", keywords: "cabeza explota sorpresa shocked face with exploding head" },
      { emoji: "🥳", name: "fiesta celebración", keywords: "fiesta celebracion face with party horn and party hat" },
      { emoji: "😎", name: "gafas de sol genial", keywords: "gafas de sol genial smiling face with sunglasses" },
      { emoji: "🤓", name: "nerd gafas", keywords: "nerd gafas nerd face" },
      { emoji: "😕", name: "confundido", keywords: "confundido confused face" },
      { emoji: "😟", name: "preocupado", keywords: "preocupado worried face" },
      { emoji: "😮", name: "boca abierta sorpresa", keywords: "boca abierta sorpresa face with open mouth" },
      { emoji: "😲", name: "asombrado", keywords: "asombrado astonished face" },
      { emoji: "😳", name: "sonrojado avergonzado", keywords: "sonrojado avergonzado flushed face" },
      { emoji: "🥺", name: "suplicante", keywords: "suplicante face with pleading eyes" },
      { emoji: "😢", name: "llorando lágrima triste", keywords: "llorando lagrima triste crying face" },
      { emoji: "😭", name: "llanto fuerte", keywords: "llanto fuerte loudly crying face" },
      { emoji: "😱", name: "grito miedo", keywords: "grito miedo face screaming in fear" },
      { emoji: "😤", name: "resoplando enojo", keywords: "resoplando enojo face with look of triumph" },
      { emoji: "😡", name: "enojado furioso", keywords: "enojado furioso pouting face" },
      { emoji: "🤬", name: "insultos furia", keywords: "insultos furia serious face with symbols covering mouth" },
      { emoji: "💀", name: "calavera", keywords: "calavera skull" },
      { emoji: "🤡", name: "payaso", keywords: "payaso clown face" },
      { emoji: "👻", name: "fantasma", keywords: "fantasma ghost" },
      { emoji: "👽", name: "extraterrestre alien", keywords: "extraterrestre alien extraterrestrial alien" },
      { emoji: "🤖", name: "robot", keywords: "robot robot face" },
      { emoji: "💩", name: "caca", keywords: "caca pile of poo" },
    ],
  },
  {
    id: "people",
    label: "Personas y gestos",
    emojis: [
      { emoji: "👋", name: "saludo mano hola", keywords: "saludo mano hola waving hand sign" },
      { emoji: "🤚", name: "mano levantada", keywords: "mano levantada raised back of hand" },
      { emoji: "✋", name: "mano alto", keywords: "mano alto raised hand" },
      { emoji: "👌", name: "ok perfecto", keywords: "ok perfecto ok hand sign" },
      { emoji: "🤌", name: "dedos juntos", keywords: "dedos juntos pinched fingers" },
      { emoji: "✌️", name: "victoria paz", keywords: "victoria paz victory hand" },
      { emoji: "🤞", name: "dedos cruzados suerte", keywords: "dedos cruzados suerte hand with index and middle fingers crossed" },
      { emoji: "🤟", name: "te quiero", keywords: "te quiero i love you hand sign" },
      { emoji: "🤘", name: "rock cuernos", keywords: "rock cuernos sign of the horns" },
      { emoji: "👈", name: "señala izquierda", keywords: "señala izquierda white left pointing backhand index" },
      { emoji: "👉", name: "señala derecha", keywords: "señala derecha white right pointing backhand index" },
      { emoji: "👆", name: "señala arriba", keywords: "señala arriba white up pointing backhand index" },
      { emoji: "👇", name: "señala abajo", keywords: "señala abajo white down pointing backhand index" },
      { emoji: "👍", name: "pulgar arriba me gusta bien", keywords: "pulgar arriba me gusta bien thumbs up sign" },
      { emoji: "👎", name: "pulgar abajo no me gusta mal", keywords: "pulgar abajo no me gusta mal thumbs down sign" },
      { emoji: "✊", name: "puño", keywords: "puño raised fist" },
      { emoji: "👊", name: "puñetazo choque", keywords: "puñetazo choque fisted hand sign" },
      { emoji: "👏", name: "aplausos", keywords: "aplausos clapping hands sign" },
      { emoji: "🙌", name: "manos arriba celebración", keywords: "manos arriba celebracion person raising both hands in celebration" },
      { emoji: "🙏", name: "por favor gracias rezar", keywords: "por favor gracias rezar person with folded hands" },
      { emoji: "🤝", name: "apretón de manos acuerdo", keywords: "apreton de manos acuerdo handshake" },
      { emoji: "💪", name: "fuerza bíceps", keywords: "fuerza biceps flexed biceps" },
      { emoji: "🧠", name: "cerebro", keywords: "cerebro brain" },
      { emoji: "👀", name: "ojos mirar", keywords: "ojos mirar eyes" },
      { emoji: "👶", name: "bebé", keywords: "bebe baby" },
      { emoji: "👩", name: "mujer", keywords: "mujer woman" },
      { emoji: "👨", name: "hombre", keywords: "hombre man" },
      { emoji: "🧑‍💻", name: "programador tecnólogo", keywords: "programador tecnologo adult personal computer" },
      { emoji: "👩‍🏫", name: "profesora docente", keywords: "profesora docente woman school" },
      { emoji: "🕺", name: "bailando", keywords: "bailando man dancing" },
    ],
  },
  {
    id: "hearts",
    label: "Corazones y símbolos",
    emojis: [
      { emoji: "❤️", name: "corazón rojo amor", keywords: "corazon rojo amor red heart heavy black heart" },
      { emoji: "🧡", name: "corazón naranja", keywords: "corazon naranja orange heart" },
      { emoji: "💛", name: "corazón amarillo", keywords: "corazon amarillo yellow heart" },
      { emoji: "💚", name: "corazón verde", keywords: "corazon verde green heart" },
      { emoji: "💙", name: "corazón azul", keywords: "corazon azul blue heart" },
      { emoji: "💜", name: "corazón violeta", keywords: "corazon violeta purple heart" },
      { emoji: "🖤", name: "corazón negro", keywords: "corazon negro black heart" },
      { emoji: "🤍", name: "corazón blanco", keywords: "corazon blanco white heart" },
      { emoji: "💔", name: "corazón roto", keywords: "corazon roto broken heart" },
      { emoji: "💕", name: "dos corazones", keywords: "dos corazones two hearts" },
      { emoji: "💯", name: "cien puntos", keywords: "cien puntos hundred points symbol" },
      { emoji: "✅", name: "hecho tilde correcto", keywords: "hecho tilde correcto white heavy check mark" },
      { emoji: "❌", name: "cruz error incorrecto", keywords: "cruz error incorrecto cross mark" },
      { emoji: "⚠️", name: "advertencia cuidado", keywords: "advertencia cuidado warning sign" },
      { emoji: "❗", name: "exclamación", keywords: "exclamacion heavy exclamation mark symbol" },
      { emoji: "❓", name: "pregunta", keywords: "pregunta black question mark ornament" },
      { emoji: "⭐", name: "estrella", keywords: "estrella white medium star" },
      { emoji: "✨", name: "brillos destellos", keywords: "brillos destellos sparkles" },
      { emoji: "🔥", name: "fuego", keywords: "fuego fire" },
      { emoji: "⚡", name: "rayo energía", keywords: "rayo energia high voltage sign" },
      { emoji: "💡", name: "idea bombilla", keywords: "idea bombilla electric light bulb" },
      { emoji: "🎯", name: "diana objetivo", keywords: "diana objetivo direct hit" },
      { emoji: "🚀", name: "cohete lanzamiento", keywords: "cohete lanzamiento rocket" },
      { emoji: "🎉", name: "fiesta confeti", keywords: "fiesta confeti party popper" },
      { emoji: "🏆", name: "trofeo premio", keywords: "trofeo premio trophy" },
      { emoji: "🔔", name: "campana notificación", keywords: "campana notificacion bell" },
      { emoji: "🔒", name: "candado cerrado", keywords: "candado cerrado lock" },
      { emoji: "🔑", name: "llave", keywords: "llave key" },
      { emoji: "♻️", name: "reciclaje", keywords: "reciclaje black universal recycling symbol" },
      { emoji: "🆕", name: "nuevo", keywords: "nuevo squared new" },
    ],
  },
  {
    id: "nature",
    label: "Animales y naturaleza",
    emojis: [
      { emoji: "🐶", name: "perro", keywords: "perro dog face" },
      { emoji: "🐱", name: "gato", keywords: "gato cat face" },
      { emoji: "🐭", name: "ratón", keywords: "raton mouse face" },
      { emoji: "🐰", name: "conejo", keywords: "conejo rabbit face" },
      { emoji: "🦊", name: "zorro", keywords: "zorro fox face" },
      { emoji: "🐻", name: "oso", keywords: "oso bear face" },
      { emoji: "🐼", name: "panda", keywords: "panda panda face" },
      { emoji: "🐨", name: "koala", keywords: "koala koala" },
      { emoji: "🐯", name: "tigre", keywords: "tigre tiger face" },
      { emoji: "🦁", name: "león", keywords: "leon lion face" },
      { emoji: "🐮", name: "vaca", keywords: "vaca cow face" },
      { emoji: "🐷", name: "cerdo", keywords: "cerdo pig face" },
      { emoji: "🐸", name: "rana", keywords: "rana frog face" },
      { emoji: "🐵", name: "mono", keywords: "mono monkey face" },
      { emoji: "🐔", name: "gallina", keywords: "gallina chicken" },
      { emoji: "🐧", name: "pingüino", keywords: "pinguino penguin" },
      { emoji: "🐦", name: "pájaro", keywords: "pajaro bird" },
      { emoji: "🦋", name: "mariposa", keywords: "mariposa butterfly" },
      { emoji: "🐝", name: "abeja", keywords: "abeja honeybee" },
      { emoji: "🐢", name: "tortuga", keywords: "tortuga turtle" },
      { emoji: "🐍", name: "serpiente", keywords: "serpiente snake" },
      { emoji: "🐙", name: "pulpo", keywords: "pulpo octopus" },
      { emoji: "🐬", name: "delfín", keywords: "delfin dolphin" },
      { emoji: "🌵", name: "cactus", keywords: "cactus cactus" },
      { emoji: "🌲", name: "árbol pino", keywords: "arbol pino evergreen tree" },
      { emoji: "🌸", name: "flor cerezo", keywords: "flor cerezo cherry blossom" },
      { emoji: "🌻", name: "girasol", keywords: "girasol sunflower" },
      { emoji: "🍀", name: "trébol suerte", keywords: "trebol suerte four leaf clover" },
      { emoji: "☀️", name: "sol", keywords: "sol black sun with rays" },
      { emoji: "🌙", name: "luna", keywords: "luna crescent moon" },
      { emoji: "🌈", name: "arcoíris", keywords: "arcoiris rainbow" },
      { emoji: "❄️", name: "nieve copo", keywords: "nieve copo snowflake" },
      { emoji: "🌊", name: "ola mar", keywords: "ola mar water wave" },
    ],
  },
  {
    id: "food",
    label: "Comida y bebida",
    emojis: [
      { emoji: "🍎", name: "manzana", keywords: "manzana red apple" },
      { emoji: "🍌", name: "banana plátano", keywords: "banana platano banana" },
      { emoji: "🍇", name: "uvas", keywords: "uvas grapes" },
      { emoji: "🍓", name: "frutilla fresa", keywords: "frutilla fresa strawberry" },
      { emoji: "🍉", name: "sandía", keywords: "sandia watermelon" },
      { emoji: "🍋", name: "limón", keywords: "limon lemon" },
      { emoji: "🥑", name: "palta aguacate", keywords: "palta aguacate avocado" },
      { emoji: "🍅", name: "tomate", keywords: "tomate tomato" },
      { emoji: "🥕", name: "zanahoria", keywords: "zanahoria carrot" },
      { emoji: "🌽", name: "maíz choclo", keywords: "maiz choclo ear of maize" },
      { emoji: "🍞", name: "pan", keywords: "pan bread" },
      { emoji: "🧀", name: "queso", keywords: "queso cheese wedge" },
      { emoji: "🍕", name: "pizza", keywords: "pizza slice of pizza" },
      { emoji: "🍔", name: "hamburguesa", keywords: "hamburguesa hamburger" },
      { emoji: "🌮", name: "taco", keywords: "taco taco" },
      { emoji: "🍣", name: "sushi", keywords: "sushi sushi" },
      { emoji: "🍝", name: "pasta fideos", keywords: "pasta fideos spaghetti" },
      { emoji: "🍰", name: "torta pastel", keywords: "torta pastel shortcake" },
      { emoji: "🍪", name: "galleta", keywords: "galleta cookie" },
      { emoji: "🍫", name: "chocolate", keywords: "chocolate chocolate bar" },
      { emoji: "☕", name: "café", keywords: "cafe hot beverage" },
      { emoji: "🍵", name: "te", keywords: "te teacup without handle" },
      { emoji: "🧉", name: "mate", keywords: "mate mate drink" },
      { emoji: "🍺", name: "cerveza", keywords: "cerveza beer mug" },
      { emoji: "🍷", name: "vino", keywords: "vino wine glass" },
      { emoji: "🥤", name: "bebida vaso", keywords: "bebida vaso cup with straw" },
    ],
  },
  {
    id: "activities",
    label: "Actividades",
    emojis: [
      { emoji: "⚽", name: "fútbol pelota", keywords: "futbol pelota soccer ball" },
      { emoji: "🏀", name: "básquet", keywords: "basquet basketball and hoop" },
      { emoji: "🎾", name: "tenis", keywords: "tenis tennis racquet and ball" },
      { emoji: "🏐", name: "vóley", keywords: "voley volleyball" },
      { emoji: "🏓", name: "ping pong", keywords: "ping pong table tennis paddle and ball" },
      { emoji: "🎮", name: "videojuego control", keywords: "videojuego control video game" },
      { emoji: "🎲", name: "dado juego", keywords: "dado juego game die" },
      { emoji: "🧩", name: "rompecabezas", keywords: "rompecabezas jigsaw puzzle piece" },
      { emoji: "🎨", name: "arte pintura", keywords: "arte pintura artist palette" },
      { emoji: "🎵", name: "música nota", keywords: "musica nota musical note" },
      { emoji: "🎸", name: "guitarra", keywords: "guitarra guitar" },
      { emoji: "🎬", name: "cine claqueta", keywords: "cine claqueta clapper board" },
      { emoji: "📚", name: "libros estudio", keywords: "libros estudio books" },
      { emoji: "🏃", name: "correr", keywords: "correr runner" },
      { emoji: "🚴", name: "bicicleta ciclismo", keywords: "bicicleta ciclismo bicyclist" },
      { emoji: "🏊", name: "natación", keywords: "natacion swimmer" },
    ],
  },
  {
    id: "travel",
    label: "Viajes y lugares",
    emojis: [
      { emoji: "🚗", name: "auto coche", keywords: "auto coche automobile" },
      { emoji: "🚌", name: "colectivo autobús", keywords: "colectivo autobus bus" },
      { emoji: "🚲", name: "bici", keywords: "bici bicycle" },
      { emoji: "✈️", name: "avión vuelo", keywords: "avion vuelo airplane" },
      { emoji: "🚆", name: "tren", keywords: "tren train" },
      { emoji: "🚢", name: "barco", keywords: "barco ship" },
      { emoji: "🏠", name: "casa hogar", keywords: "casa hogar house building" },
      { emoji: "🏢", name: "oficina edificio", keywords: "oficina edificio office building" },
      { emoji: "🏫", name: "escuela", keywords: "escuela school" },
      { emoji: "🏥", name: "hospital", keywords: "hospital hospital" },
      { emoji: "🌍", name: "mundo tierra", keywords: "mundo tierra earth globe europe-africa" },
      { emoji: "🗺️", name: "mapa", keywords: "mapa world map" },
      { emoji: "📍", name: "ubicación pin", keywords: "ubicacion pin round pushpin" },
      { emoji: "⛰️", name: "montaña", keywords: "montaña mountain" },
      { emoji: "🏖️", name: "playa", keywords: "playa beach with umbrella" },
      { emoji: "🕒", name: "hora reloj", keywords: "hora reloj clock face three oclock" },
    ],
  },
  {
    id: "objects",
    label: "Objetos",
    emojis: [
      { emoji: "💻", name: "computadora portátil", keywords: "computadora portatil personal computer" },
      { emoji: "🖥️", name: "monitor pantalla", keywords: "monitor pantalla desktop computer" },
      { emoji: "📱", name: "celular teléfono", keywords: "celular telefono mobile phone" },
      { emoji: "⌨️", name: "teclado", keywords: "teclado keyboard" },
      { emoji: "🖱️", name: "mouse ratón", keywords: "mouse raton three button mouse" },
      { emoji: "🖨️", name: "impresora", keywords: "impresora printer" },
      { emoji: "📷", name: "cámara foto", keywords: "camara foto camera" },
      { emoji: "📞", name: "teléfono llamada", keywords: "telefono llamada telephone receiver" },
      { emoji: "✉️", name: "sobre correo email", keywords: "sobre correo email envelope" },
      { emoji: "📦", name: "paquete caja envío", keywords: "paquete caja envio package" },
      { emoji: "📝", name: "nota escribir", keywords: "nota escribir memo" },
      { emoji: "📌", name: "chinche fijar", keywords: "chinche fijar pushpin" },
      { emoji: "📎", name: "clip adjunto", keywords: "clip adjunto paperclip" },
      { emoji: "✂️", name: "tijera", keywords: "tijera black scissors" },
      { emoji: "🔍", name: "lupa buscar", keywords: "lupa buscar left-pointing magnifying glass" },
      { emoji: "📅", name: "calendario fecha", keywords: "calendario fecha calendar" },
      { emoji: "📈", name: "gráfico subida", keywords: "grafico subida chart with upwards trend" },
      { emoji: "📉", name: "gráfico bajada", keywords: "grafico bajada chart with downwards trend" },
      { emoji: "📊", name: "gráfico barras", keywords: "grafico barras bar chart" },
      { emoji: "💰", name: "dinero bolsa", keywords: "dinero bolsa money bag" },
      { emoji: "💳", name: "tarjeta crédito pago", keywords: "tarjeta credito pago credit card" },
      { emoji: "🧾", name: "recibo factura", keywords: "recibo factura receipt" },
      { emoji: "🛒", name: "carrito compras", keywords: "carrito compras shopping trolley" },
      { emoji: "🎁", name: "regalo", keywords: "regalo wrapped present" },
      { emoji: "🔧", name: "llave inglesa herramienta", keywords: "llave inglesa herramienta wrench" },
      { emoji: "⚙️", name: "engranaje configuración", keywords: "engranaje configuracion gear" },
      { emoji: "🗑️", name: "tacho basura eliminar", keywords: "tacho basura eliminar wastebasket" },
    ],
  },
];
